In [23]:
import os
import pandas as pd

folder_path = "/Users/yash/algothon-26/man-imperial-algothon-2026/data/2024-12-31"

dfs = {}

for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        file_path = os.path.join(folder_path, file)
        df_name = file.replace(".csv", "")
        dfs[df_name] = pd.read_csv(file_path)
        print(f'{df_name}')
        print(dfs[df_name].head())

cash_rate
         date  1mo  1.5month  2mo   3mo  4mo   6mo   1yr   2yr   3yr   5yr  \
0  1990-01-02  NaN       NaN  NaN  7.83  NaN  7.89  7.81  7.87  7.90  7.87
1  1990-01-03  NaN       NaN  NaN  7.89  NaN  7.94  7.85  7.94  7.96  7.92
2  1990-01-04  NaN       NaN  NaN  7.84  NaN  7.90  7.82  7.92  7.93  7.91
3  1990-01-05  NaN       NaN  NaN  7.79  NaN  7.85  7.79  7.90  7.94  7.92
4  1990-01-08  NaN       NaN  NaN  7.79  NaN  7.88  7.81  7.90  7.95  7.92

    7yr  10yr  20yr  30yr
0  7.98  7.94   NaN  8.00
1  8.04  7.99   NaN  8.04
2  8.02  7.98   NaN  8.04
3  8.03  7.99   NaN  8.06
4  8.05  8.02   NaN  8.09
prices
         date  INSTRUMENT_1  INSTRUMENT_2  INSTRUMENT_3  INSTRUMENT_4  \
0  2017-01-03        196.68        112.72         49.97         29.81
1  2017-01-04        197.85        113.32         50.53         30.04
2  2017-01-05        197.71        113.93         50.96         30.36
3  2017-01-06        198.39        114.93         50.79         30.24
4  2017-01-09        197.78        115.32         50.71         30.21

   INSTRUMENT_5  INSTRUMENT_6  INSTRUMENT_7  INSTRUMENT_8  INSTRUMENT_9  \
0         96.29         96.91        110.47         91.52       4285.08
1         96.66         97.02        110.86         92.63       4285.41
2         98.21         97.69        112.59         93.60       4286.03
3         97.29         97.22        111.76         93.44       4286.33
4         98.10         97.61        112.69         90.47       4287.06

   INSTRUMENT_10
0         302.00
1         301.90
2         301.83
3         301.89
4         301.92
signals
         date  INSTRUMENT_1_trend4  INSTRUMENT_1_trend8  INSTRUMENT_1_trend16  \
0  2017-01-03                  NaN                  NaN                   NaN
1  2017-01-04                  NaN                  NaN                   NaN
2  2017-01-05                  NaN                  NaN                   NaN
3  2017-01-06                  NaN                  NaN                   NaN
4  2017-01-09                  NaN                  NaN                   NaN

   INSTRUMENT_1_trend32  INSTRUMENT_2_trend4  INSTRUMENT_2_trend8  \
0                   NaN                  NaN                  NaN
1                   NaN                  NaN                  NaN
2                   NaN                  NaN                  NaN
3                   NaN                  NaN                  NaN
4                   NaN                  NaN                  NaN

   INSTRUMENT_2_trend16  INSTRUMENT_2_trend32  INSTRUMENT_3_trend4  ...  \
0                   NaN                   NaN                  NaN  ...
1                   NaN                   NaN                  NaN  ...
2                   NaN                   NaN                  NaN  ...
3                   NaN                   NaN                  NaN  ...
4                   NaN                   NaN                  NaN  ...

   INSTRUMENT_8_trend16  INSTRUMENT_8_trend32  INSTRUMENT_9_trend4  \
0                   NaN                   NaN                  NaN
1                   NaN                   NaN                  NaN
2                   NaN                   NaN                  NaN
3                   NaN                   NaN                  NaN
4                   NaN                   NaN                  NaN

   INSTRUMENT_9_trend8  INSTRUMENT_9_trend16  INSTRUMENT_9_trend32  \
0                  NaN                   NaN                   NaN
1                  NaN                   NaN                   NaN
2                  NaN                   NaN                   NaN
3                  NaN                   NaN                   NaN
4                  NaN                   NaN                   NaN

   INSTRUMENT_10_trend4  INSTRUMENT_10_trend8  INSTRUMENT_10_trend16  \
0                   NaN                   NaN                    NaN
1                   NaN                   NaN                    NaN
2                   NaN                   NaN                    NaN
3                   NaN                   NaN                    NaN
4                   NaN                   NaN                    NaN

   INSTRUMENT_10_trend32
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN

[5 rows x 41 columns]
volumes
         date  INSTRUMENT_1_vol  INSTRUMENT_2_vol  INSTRUMENT_3_vol  \
0  2017-01-03         104295938          21702365          31368597
1  2017-01-04          98727275          16544270          30654856
2  2017-01-05          96566373          18301731          25091271
3  2017-01-06          80944775          23197256          26329515
4  2017-01-09          54386881          17323841          15168291

   INSTRUMENT_4_vol  INSTRUMENT_5_vol  INSTRUMENT_6_vol  INSTRUMENT_7_vol  \
0          80644865          15086731           3813373           7761916
1          98880894           8022393           1627154           4656791
2          70038101          16694891           3784244          10153154
3          42522230           9575889           1617186           8311165
4          37682598           9779728           1345935           5508510

   INSTRUMENT_8_vol  INSTRUMENT_9_vol  INSTRUMENT_10_vol
0           4322207                 0                  0
1           2292779                 0                  0
2           2634431                 0                  0
3           2066255                 0                  0
4           2583137                 0                  0

In [24]:
dfs.keys()

dict_keys(['cash_rate', 'prices', 'signals', 'volumes'])

In [25]:
dfs['cash_rate']

,date,1mo,1.5month,2mo,3mo,4mo,6mo,1yr,2yr,3yr,5yr,7yr,10yr,20yr,30yr
0,1990-01-02,NaN,NaN,NaN,7.83,NaN,7.89,7.81,7.87,7.90,7.87,7.98,7.94,NaN,8.00
1,1990-01-03,NaN,NaN,NaN,7.89,NaN,7.94,7.85,7.94,7.96,7.92,8.04,7.99,NaN,8.04
2,1990-01-04,NaN,NaN,NaN,7.84,NaN,7.90,7.82,7.92,7.93,7.91,8.02,7.98,NaN,8.04
3,1990-01-05,NaN,NaN,NaN,7.79,NaN,7.85,7.79,7.90,7.94,7.92,8.03,7.99,NaN,8.06
4,1990-01-08,NaN,NaN,NaN,7.79,NaN,7.88,7.81,7.90,7.95,7.92,8.05,8.02,NaN,8.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8752,2024-12-24,4.44,NaN,4.44,4.40,4.38,4.30,4.24,4.29,4.36,4.43,4.52,4.59,4.84,4.76
8753,2024-12-26,4.45,NaN,4.45,4.35,4.37,4.31,4.23,4.30,4.35,4.42,4.49,4.58,4.83,4.76
8754,2024-12-27,4.44,NaN,4.43,4.31,4.35,4.29,4.20,4.31,4.36,4.45,4.53,4.62,4.89,4.82
8755,2024-12-30,4.43,NaN,4.42,4.37,4.33,4.25,4.17,4.24,4.29,4.37,4.46,4.55,4.84,4.77
8756,2024-12-31,4.40,NaN,4.39,4.37,4.32,4.24,4.16,4.25,4.27,4.38,4.48,4.58,4.86,4.78

In [32]:
nan_counts = dfs['cash_rate'].isna().sum()
print(nan_counts)

date           0
1mo         2900
1.5month    8757
2mo         7205
3mo            4
4mo         8207
6mo            1
1yr            1
2yr            1
3yr            1
5yr            1
7yr            1
10yr           1
20yr         940
30yr         995
dtype: int64

In [26]:
dfs['prices']

,date,INSTRUMENT_1,INSTRUMENT_2,INSTRUMENT_3,INSTRUMENT_4,INSTRUMENT_5,INSTRUMENT_6,INSTRUMENT_7,INSTRUMENT_8,INSTRUMENT_9,INSTRUMENT_10
0,2017-01-03,196.68,112.72,49.97,29.81,96.29,96.91,110.47,91.52,4285.08,302.00
1,2017-01-04,197.85,113.32,50.53,30.04,96.66,97.02,110.86,92.63,4285.41,301.90
2,2017-01-05,197.71,113.93,50.96,30.36,98.21,97.69,112.59,93.60,4286.03,301.83
3,2017-01-06,198.39,114.93,50.79,30.24,97.29,97.22,111.76,93.44,4286.33,301.89
4,2017-01-09,197.78,115.32,50.71,30.21,98.10,97.61,112.69,90.47,4287.06,301.92
...,...,...,...,...,...,...,...,...,...,...,...
2846,2024-12-27,590.83,521.98,75.89,42.15,85.69,92.32,242.01,74.96,94534.81,3354.00
2847,2024-12-28,590.82,521.97,75.88,42.16,85.69,92.31,241.99,74.96,95517.90,3425.51
2848,2024-12-29,590.80,522.03,75.89,42.16,85.69,92.31,241.98,74.96,93933.57,3378.68
2849,2024-12-30,584.08,515.12,75.39,41.82,86.38,92.86,241.20,75.94,92988.75,3383.45
2850,2024-12-31,581.98,510.77,75.39,41.68,85.92,92.69,242.70,76.68,93783.04,3358.44

In [27]:
dfs['signals']

,date,INSTRUMENT_1_trend4,INSTRUMENT_1_trend8,INSTRUMENT_1_trend16,INSTRUMENT_1_trend32,INSTRUMENT_2_trend4,INSTRUMENT_2_trend8,INSTRUMENT_2_trend16,INSTRUMENT_2_trend32,INSTRUMENT_3_trend4,...,INSTRUMENT_8_trend16,INSTRUMENT_8_trend32,INSTRUMENT_9_trend4,INSTRUMENT_9_trend8,INSTRUMENT_9_trend16,INSTRUMENT_9_trend32,INSTRUMENT_10_trend4,INSTRUMENT_10_trend8,INSTRUMENT_10_trend16,INSTRUMENT_10_trend32
0,2017-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2846,2024-12-27,-0.078409,-0.083091,0.208100,0.284502,-0.043356,0.055395,0.267373,0.174283,-0.369598,...,0.016689,-0.021199,-0.194311,0.136771,1.016092,0.983661,-0.316647,-0.001876,0.998152,0.608948
2847,2024-12-28,-0.006317,-0.054032,0.186249,0.339500,0.031746,0.067864,0.221795,0.248310,-0.284034,...,-0.042398,-0.087502,-0.043856,0.178758,1.029229,0.975964,-0.300067,0.111469,1.110746,0.544104
2848,2024-12-29,-0.005500,-0.040505,0.185358,0.282942,0.002580,0.096171,0.250747,0.183241,-0.264628,...,0.003608,-0.171396,-0.063402,0.043323,1.061030,0.982477,-0.315498,-0.244979,1.097283,0.691560
2849,2024-12-30,-0.005574,-0.040208,0.185506,0.282496,-0.000287,0.096171,0.250962,0.183169,-0.233755,...,0.003608,-0.172298,-0.176007,-0.014236,1.031790,0.970751,-0.411834,-0.231692,1.048629,0.630530
2850,2024-12-31,-0.052322,-0.041397,0.172128,0.309846,-0.050737,0.100542,0.250389,0.215131,-0.242576,...,0.177259,-0.177710,-0.315060,-0.080216,1.065845,1.024414,-0.481075,-0.132714,1.070922,0.657962

In [28]:
dfs['volumes']

,date,INSTRUMENT_1_vol,INSTRUMENT_2_vol,INSTRUMENT_3_vol,INSTRUMENT_4_vol,INSTRUMENT_5_vol,INSTRUMENT_6_vol,INSTRUMENT_7_vol,INSTRUMENT_8_vol,INSTRUMENT_9_vol,INSTRUMENT_10_vol
0,2017-01-03,104295938,21702365,31368597,80644865,15086731,3813373,7761916,4322207,0,0
1,2017-01-04,98727275,16544270,30654856,98880894,8022393,1627154,4656791,2292779,0,0
2,2017-01-05,96566373,18301731,25091271,70038101,16694891,3784244,10153154,2634431,0,0
3,2017-01-06,80944775,23197256,26329515,42522230,9575889,1617186,8311165,2066255,0,0
4,2017-01-09,54386881,17323841,15168291,37682598,9779728,1345935,5508510,2583137,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2846,2024-12-27,61967617,33502226,16868899,24225146,28636460,3920164,4420500,1337711,26008,357697
2847,2024-12-28,0,0,0,0,0,0,0,0,7888,167303
2848,2024-12-29,0,0,0,0,0,0,0,0,12490,153502
2849,2024-12-30,54624660,34416033,15936284,25619659,48515430,4410007,3412877,1523595,30272,421763
2850,2024-12-31,59133138,29020647,23355138,37969104,31200404,6182257,2456821,1226087,19061,332325

In [29]:
dfs = {}
cleaned_dfs = {}

for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        file_path = os.path.join(folder_path, file)
        df_name = file.replace(".csv", "")
        
        df = pd.read_csv(file_path)        
        date_col = None
        for col in df.columns:
            if "date" in col.lower() or "time" in col.lower():
                date_col = col
                df[col] = pd.to_datetime(df[col], errors="coerce")
                df = df.sort_values(col)
                break
        
        original_rows = len(df)
        # drop rows where any column has a nan
        df_clean = df.dropna(axis=1, how="any")
        cleaned_rows = len(df_clean)
        dfs[df_name] = df
        cleaned_dfs[df_name] = df_clean
        print(df_clean.head())

        date
0 1990-01-02
1 1990-01-03
2 1990-01-04
3 1990-01-05
4 1990-01-08
        date  INSTRUMENT_1  INSTRUMENT_2  INSTRUMENT_3  INSTRUMENT_4  \
0 2017-01-03        196.68        112.72         49.97         29.81
1 2017-01-04        197.85        113.32         50.53         30.04
2 2017-01-05        197.71        113.93         50.96         30.36
3 2017-01-06        198.39        114.93         50.79         30.24
4 2017-01-09        197.78        115.32         50.71         30.21

   INSTRUMENT_5  INSTRUMENT_6  INSTRUMENT_7  INSTRUMENT_8  INSTRUMENT_9  \
0         96.29         96.91        110.47         91.52       4285.08
1         96.66         97.02        110.86         92.63       4285.41
2         98.21         97.69        112.59         93.60       4286.03
3         97.29         97.22        111.76         93.44       4286.33
4         98.10         97.61        112.69         90.47       4287.06

   INSTRUMENT_10
0         302.00
1         301.90
2         301.83
3         301.89
4         301.92
        date
0 2017-01-03
1 2017-01-04
2 2017-01-05
3 2017-01-06
4 2017-01-09
        date  INSTRUMENT_1_vol  INSTRUMENT_2_vol  INSTRUMENT_3_vol  \
0 2017-01-03         104295938          21702365          31368597
1 2017-01-04          98727275          16544270          30654856
2 2017-01-05          96566373          18301731          25091271
3 2017-01-06          80944775          23197256          26329515
4 2017-01-09          54386881          17323841          15168291

   INSTRUMENT_4_vol  INSTRUMENT_5_vol  INSTRUMENT_6_vol  INSTRUMENT_7_vol  \
0          80644865          15086731           3813373           7761916
1          98880894           8022393           1627154           4656791
2          70038101          16694891           3784244          10153154
3          42522230           9575889           1617186           8311165
4          37682598           9779728           1345935           5508510

   INSTRUMENT_8_vol  INSTRUMENT_9_vol  INSTRUMENT_10_vol
0           4322207                 0                  0
1           2292779                 0                  0
2           2634431                 0                  0
3           2066255                 0                  0
4           2583137                 0                  0

In [30]:
cleaned_dfs.keys()

dict_keys(['cash_rate', 'prices', 'signals', 'volumes'])

In [31]:
cleaned_dfs['cash_rate']

           date
0    1990-01-02
1    1990-01-03
2    1990-01-04
3    1990-01-05
4    1990-01-08
...         ...
8752 2024-12-24
8753 2024-12-26
8754 2024-12-27
8755 2024-12-30
8756 2024-12-31

[8757 rows x 1 columns]

In [16]:
cleaned_dfs['prices']

,date,INSTRUMENT_1,INSTRUMENT_2,INSTRUMENT_3,INSTRUMENT_4,INSTRUMENT_5,INSTRUMENT_6,INSTRUMENT_7,INSTRUMENT_8,INSTRUMENT_9,INSTRUMENT_10
0,2017-01-03,196.68,112.72,49.97,29.81,96.29,96.91,110.47,91.52,4285.08,302.00
1,2017-01-04,197.85,113.32,50.53,30.04,96.66,97.02,110.86,92.63,4285.41,301.90
2,2017-01-05,197.71,113.93,50.96,30.36,98.21,97.69,112.59,93.60,4286.03,301.83
3,2017-01-06,198.39,114.93,50.79,30.24,97.29,97.22,111.76,93.44,4286.33,301.89
4,2017-01-09,197.78,115.32,50.71,30.21,98.10,97.61,112.69,90.47,4287.06,301.92
...,...,...,...,...,...,...,...,...,...,...,...
2846,2024-12-27,590.83,521.98,75.89,42.15,85.69,92.32,242.01,74.96,94534.81,3354.00
2847,2024-12-28,590.82,521.97,75.88,42.16,85.69,92.31,241.99,74.96,95517.90,3425.51
2848,2024-12-29,590.80,522.03,75.89,42.16,85.69,92.31,241.98,74.96,93933.57,3378.68
2849,2024-12-30,584.08,515.12,75.39,41.82,86.38,92.86,241.20,75.94,92988.75,3383.45
2850,2024-12-31,581.98,510.77,75.39,41.68,85.92,92.69,242.70,76.68,93783.04,3358.44

In [17]:
cleaned_dfs['signals']

,date,INSTRUMENT_1_trend4,INSTRUMENT_1_trend8,INSTRUMENT_1_trend16,INSTRUMENT_1_trend32,INSTRUMENT_2_trend4,INSTRUMENT_2_trend8,INSTRUMENT_2_trend16,INSTRUMENT_2_trend32,INSTRUMENT_3_trend4,...,INSTRUMENT_8_trend16,INSTRUMENT_8_trend32,INSTRUMENT_9_trend4,INSTRUMENT_9_trend8,INSTRUMENT_9_trend16,INSTRUMENT_9_trend32,INSTRUMENT_10_trend4,INSTRUMENT_10_trend8,INSTRUMENT_10_trend16,INSTRUMENT_10_trend32
128,2017-07-07,-0.008324,0.031884,0.060944,0.099368,-0.011896,0.012828,0.051740,0.132862,-0.020288,...,-0.519599,-0.322043,-0.000068,-0.000054,0.000029,0.000219,0.000115,-0.000168,0.000008,0.000904
129,2017-07-10,-0.002378,0.015533,0.053437,0.093868,-0.017414,-0.005375,0.047154,0.129566,0.025581,...,-0.603042,-0.335575,-0.000042,-0.000052,0.000024,0.000212,0.000146,-0.000123,-0.000161,0.000934
130,2017-07-11,0.001115,0.026458,0.055146,0.098476,-0.004730,0.003726,0.043714,0.129494,-0.016760,...,-0.617926,-0.393759,0.000027,-0.000093,0.000019,0.000193,0.000146,-0.000161,-0.000199,0.001026
131,2017-07-12,-0.026384,0.004459,0.067410,0.101151,-0.028522,-0.020639,0.058978,0.130354,-0.059982,...,-0.726176,-0.588609,0.000006,-0.000111,0.000041,0.000186,0.000153,-0.000191,-0.000283,0.001049
132,2017-07-13,-0.005723,0.007952,0.058565,0.105313,-0.011036,-0.022072,0.055323,0.129279,-0.019406,...,-0.798794,-0.367598,-0.000013,-0.000123,0.000019,0.000187,0.000130,-0.000130,-0.000306,0.000996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2846,2024-12-27,-0.078409,-0.083091,0.208100,0.284502,-0.043356,0.055395,0.267373,0.174283,-0.369598,...,0.016689,-0.021199,-0.194311,0.136771,1.016092,0.983661,-0.316647,-0.001876,0.998152,0.608948
2847,2024-12-28,-0.006317,-0.054032,0.186249,0.339500,0.031746,0.067864,0.221795,0.248310,-0.284034,...,-0.042398,-0.087502,-0.043856,0.178758,1.029229,0.975964,-0.300067,0.111469,1.110746,0.544104
2848,2024-12-29,-0.005500,-0.040505,0.185358,0.282942,0.002580,0.096171,0.250747,0.183241,-0.264628,...,0.003608,-0.171396,-0.063402,0.043323,1.061030,0.982477,-0.315498,-0.244979,1.097283,0.691560
2849,2024-12-30,-0.005574,-0.040208,0.185506,0.282496,-0.000287,0.096171,0.250962,0.183169,-0.233755,...,0.003608,-0.172298,-0.176007,-0.014236,1.031790,0.970751,-0.411834,-0.231692,1.048629,0.630530
2850,2024-12-31,-0.052322,-0.041397,0.172128,0.309846,-0.050737,0.100542,0.250389,0.215131,-0.242576,...,0.177259,-0.177710,-0.315060,-0.080216,1.065845,1.024414,-0.481075,-0.132714,1.070922,0.657962

In [18]:
cleaned_dfs['volumes']

,date,INSTRUMENT_1_vol,INSTRUMENT_2_vol,INSTRUMENT_3_vol,INSTRUMENT_4_vol,INSTRUMENT_5_vol,INSTRUMENT_6_vol,INSTRUMENT_7_vol,INSTRUMENT_8_vol,INSTRUMENT_9_vol,INSTRUMENT_10_vol
0,2017-01-03,104295938,21702365,31368597,80644865,15086731,3813373,7761916,4322207,0,0
1,2017-01-04,98727275,16544270,30654856,98880894,8022393,1627154,4656791,2292779,0,0
2,2017-01-05,96566373,18301731,25091271,70038101,16694891,3784244,10153154,2634431,0,0
3,2017-01-06,80944775,23197256,26329515,42522230,9575889,1617186,8311165,2066255,0,0
4,2017-01-09,54386881,17323841,15168291,37682598,9779728,1345935,5508510,2583137,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2846,2024-12-27,61967617,33502226,16868899,24225146,28636460,3920164,4420500,1337711,26008,357697
2847,2024-12-28,0,0,0,0,0,0,0,0,7888,167303
2848,2024-12-29,0,0,0,0,0,0,0,0,12490,153502
2849,2024-12-30,54624660,34416033,15936284,25619659,48515430,4410007,3412877,1523595,30272,421763
2850,2024-12-31,59133138,29020647,23355138,37969104,31200404,6182257,2456821,1226087,19061,332325